# Generated by Django 5.1.5 on 2025-01-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField()),
                ('post_content', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
