# Generated by Django 5.1.5 on 2025-04-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
