# Generated by Django 5.1.5 on 2025-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
