# Generated by Django 5.1.5 on 2025-01-31 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postmodel_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
