# Generated by Django 5.1.5 on 2025-02-03 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postmodel_post_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
