# Generated by Django 5.1.5 on 2025-02-04 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postmodel_post_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_desc', models.CharField(max_length=200)),
                ('com_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('com_likes', models.PositiveIntegerField(default=0)),
                ('com_reply', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Replier', to=settings.AUTH_USER_MODEL)),
                ('com_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postmodel')),
            ],
        ),
    ]
