# Generated by Django 5.1.5 on 2025-02-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_postcomments_com_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='post_id',
            new_name='post',
        ),
    ]
