# Generated by Django 5.1.5 on 2025-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_rename_post_id_postcomments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='reply_on_comment',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
