# Generated by Django 5.1.5 on 2025-04-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_postcomments_com_user_alter_postcomments_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
