# Generated by Django 5.1.5 on 2025-04-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_postcomments_created_at_postlikes_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='created_at',
        ),
    ]
