# Generated by Django 5.1.5 on 2025-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('about', models.TextField()),
                ('siblings', models.IntegerField(default=20)),
                ('marks', models.FloatField()),
                ('indian', models.BooleanField()),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
