# Generated by Django 5.1.5 on 2025-04-09 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('testing', '0001_initial'), ('testing', '0002_demotable_password_alter_demotable_created_at'), ('testing', '0003_rename_password_demotable_password1'), ('testing', '0004_alter_demotable_password1_alter_demotable_siblings')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('about', models.TextField()),
                ('siblings', models.IntegerField(default=5)),
                ('marks', models.FloatField()),
                ('indian', models.BooleanField()),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=20)),
            ],
        ),
    ]
