# Generated by Django 5.1.5 on 2025-04-08 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demotable',
            name='password',
            field=models.CharField(default='@@123456', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demotable',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
