# Generated by Django 5.1.5 on 2025-04-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_demotable_password_alter_demotable_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demotable',
            old_name='password',
            new_name='password1',
        ),
    ]
