# Generated by Django 5.1.5 on 2025-04-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_rename_password_demotable_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='password1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='siblings',
            field=models.IntegerField(default=5),
        ),
    ]
