# Generated by Django 5.1.5 on 2025-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_demotable_password1_alter_demotable_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='demotable',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
