# Generated by Django 5.1.5 on 2025-04-09 11:52

from django.db import migrations


def myFunction(apps, schema_editor):
    DemoTable = apps.get_model('testing', 'DemoTable')
    for demo in DemoTable.objects.all():
        demo.city = "Neemuch"
        demo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_demotable_city'),
    ]

    operations = [
        migrations.RunPython(myFunction)
    ]
