# Generated by Django 5.1.5 on 2025-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20250409_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='demotable',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
